// <auto-generated />
using APIproje.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIproje.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIproje.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 500m,
                            ProductName = "Test"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 600m,
                            ProductName = "Test 2"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = true,
                            Price = 700m,
                            ProductName = "Test 3"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 800m,
                            ProductName = "Test 4"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            Price = 900m,
                            ProductName = "Test 5"
                        },
                        new
                        {
                            ProductId = 6,
                            IsActive = true,
                            Price = 1000m,
                            ProductName = "Test 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
